# Generated by Django 5.1.2 on 2024-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Varans namn'),
        ),
    ]
